# Generated by Django 5.2.4 on 2025-07-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_userroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='room',
            name='require_pin_everytime',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userroom',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
