# Generated by Django 5.2.4 on 2025-08-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroom',
            name='authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
