# Generated by Django 5.2.4 on 2025-08-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_userroom_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pin_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
