# Generated by Django 5.2.4 on 2025-08-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_room_pin_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroom',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='userroom',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
