# Generated by Django 4.2.23 on 2025-08-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_remove_userroom_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='posts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userroom',
            name='authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
