"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# ---------------------------
# 기본 경로 및 환경 변수 로드
# ---------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
CONFIG_DIR = Path(__file__).resolve().parent
load_dotenv(CONFIG_DIR / ".env")

# ---------------------------
# 환경 변수
# ---------------------------
NAVER_CLIENT_ID = os.getenv("NAVER_CLIENT_ID")
NAVER_CLIENT_SECRET = os.getenv("NAVER_CLIENT_SECRET")
NAVER_CALLBACK_URL = os.getenv("NAVER_CALLBACK_URL")

# ---------------------------
# 사용자 인증 설정
# ---------------------------
AUTH_USER_MODEL = 'user.User'
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# ---------------------------
# Django 기본 앱 + 커스텀 앱
# ---------------------------
INSTALLED_APPS = [
    # Django 기본 앱
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 내가 만든 앱
    'user',
    'main_page',
    'board',

    # 서드파티 앱
    'storages',
]

# ---------------------------
# 미들웨어
# ---------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ---------------------------
# URL / WSGI
# ---------------------------
ROOT_URLCONF = 'myproject.urls'
WSGI_APPLICATION = 'myproject.wsgi.application'

# ---------------------------
# 템플릿 설정
# ---------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ---------------------------
# 데이터베이스
# ---------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ---------------------------
# 비밀번호 검증
# ---------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ---------------------------
# 국제화
# ---------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Seoul'
USE_I18N = True
USE_TZ = True

# ---------------------------
# 정적 파일
# ---------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'myproject' / 'static',
]

# ---------------------------
# 기본 PK 타입
# ---------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------
# NCP Object Storage (S3 호환)
# ---------------------------
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
}

AWS_ACCESS_KEY_ID = os.getenv("NCP_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("NCP_SECRET_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("NCP_BUCKET")
AWS_S3_REGION_NAME = os.getenv("NCP_REGION", "kr-standard")
AWS_S3_ENDPOINT_URL = os.getenv("NCP_ENDPOINT", "https://kr.object.ncloudstorage.com")
AWS_S3_SIGNATURE_VERSION = "s3v4"

# 업로드 기본 ACL (운영 환경에서는 private 권장)
AWS_DEFAULT_ACL = "public-read"

# 미디어 파일 URL
MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.kr.object.ncloudstorage.com/"
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# ---------------------------
# 개발 모드 설정
# ---------------------------
SECRET_KEY = 'django-insecure-dw*^9&r6pzx#=g%bf@4fln294lcbte$buadpu)_(!i7dxnoa5d'
DEBUG = True
ALLOWED_HOSTS = ['*']
