# Generated by Django 5.2.4 on 2025-07-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.png', upload_to='user_profile_image_path'),
        ),
    ]
