# Generated by Django 5.2.4 on 2025-07-31 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_phone_num',
        ),
    ]
