# Generated by Django 5.2.4 on 2025-08-09 03:09

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_user_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_image',
            field=models.ImageField(blank=True, default='images/default_profile.png', upload_to=user.models.user_profile_image_path),
        ),
    ]
